name: DevSecOps - Trivy Security Scan

permissions:
  contents: read
  security-events: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  trivy-filesystem-scan:
    name: Filesystem Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-fs-results.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true

      - name: Upload Filesystem Scan Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs-results.sarif


  trivy-config-scan:
    name: Dockerfile & Config Scan
    runs-on: ubuntu-latest
    needs: trivy-filesystem-scan

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Trivy Config Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: ./wazuh-docker-4.7.5
          format: sarif
          output: trivy-config-results.sarif
          severity: HIGH,CRITICAL

      - name: Upload Config Scan Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-config-results.sarif
